# -*- coding: utf-8 -*-
"""Election streamer.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fH1lXkGCIjRtodLomtVEkZdWHBO_xO_V
"""

# -*- coding: utf-8 -*-
"""
Created on Thur Oct 21 14:01:11 2022

@author: Nneka.Anioko
"""

from twython import TwythonStreamer
import csv
def process_tweet(tweet):
    d = {}
    d['hashtags'] = [hashtag['text'] for hashtag in tweet['entities']['hashtags']]
    d['text'] = tweet['text']
    d['user'] = tweet['user']['screen_name']
    d['user_loc'] = tweet['user']['location']
    d['source'] = tweet['source']
    d['Created_at'] = tweet['user']['created_at']
    d['user_followers_count'] = tweet['user']['followers_count']
    d['user_following_count'] = tweet['user']['following']
    d['user_verified'] = tweet['user']['verified']
    d['place'] = tweet['place']
    d['geo'] = tweet['geo']
    d['created_at'] = tweet['created_at']
    return d

         
2
class MyStreamer(TwythonStreamer):
    def on_success(self, election_tweets):
        if election_tweets['lang'] == 'en':
            tweet_data = process_tweet(election_tweets)
            print(tweet_data)
            self.save_to_csv(tweet_data)
   
    
    def on_error(self, status_code, election_tweets,):
        print(status_code, election_tweets)
        self.disconnect()
    
    def save_to_csv(self, election_tweets):
        with open(r'Tinubu.csv', 'a', encoding='utf-8') as file:
            writer = csv.writer(file)
            writer.writerow(list(election_tweets.values()))
               
               
            
    
#load credential from the json file we created 

import json
with open('twitter_credentials.json', 'r') as file:
    creds = json.load(file)
    
stream = MyStreamer(creds['CONSUMER_KEY'], creds['CONSUMER_SECRET'],
                    creds['ACCESS_TOKEN'], creds['ACCESS_SECRET'])

stream.statuses.filter(track='Tinubu')